name: py-api

replicaCount: 1

image:
  repository: docker.io/vikagumi/py-api
  digest: ""          # CI / env values will override this
  pullPolicy: IfNotPresent

service:
  port: 8000
  targetPort: 8000

monitoring:
  enabled: true
  serviceMonitor:
    namespace: monitoring
    selectorLabels:
      release: kube-prometheus-stack   # must match your Prometheus
  errorRateThreshold: 0.05